### PR TITLE
add subtle detail to Combine doc comment

### PR DESCRIPTION
**Pull request by ifraixedes**

### CODE REVIEW

**Comment by ifraixedes** [comment]
Go ahead an merged because I cannot do it.

**Comment by zeebo** [comment]
It's not letting me do it either :(

My merge view

**Comment by ifraixedes** [comment]
I'll repush it

**Comment by ifraixedes** [comment]
No idea what happened, probably I messed up something at some point, because the branch wasn't present in my repo.

You should be able to merge it now.

**Pull request merged**
